{% set name = "plus_sync" %}
{% set version = "0.7.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plus_sync-{{ version }}.tar.gz
  sha256: e3da0b92e391a5a92b45a1b1f6eb1b250c773f288db131b5e571ccd884f896b5

build:
  entry_points:
    - plus_sync = plus_sync.cmd:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >={{ python_min }}
    - paramiko
    - attrs
    - cattrs
    - attrs-strict
    - tomlkit
    - typer
    - python-gitlab
    - tqdm
    - joblib
    - quickxorhash
    - factory_boy
    - click < 8.2

test:
  imports:
    - plus_sync
  commands:
    - pip check
    - plus_sync --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Convenient command line tool to sync all kind of data.
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://gitlab.com/thht/plus_sync
  description: |
    `plus_sync` is a command line tool to make it easier to synchronize data. It was built with a HPC, more specifically the SCC at the PLUS, setup in mind.
    You can find some documentation here: https://gitlab.com/thht/plus_sync

extra:
  recipe-maintainers:
    - thht
